version: "3.5"
services:
  app:
    image: ghcr.io/sapporo-wes/sapporo-service:1.3.1
    container_name: sapporo-service
    volumes:
      # The ones below are mounted for cwltool and DinD.
      - ${PWD}/run:${PWD}/run
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      # デモ用に追加
      - ${PWD}/executable_workflows.json:/demo-params/executable_workflows.json
    environment:
      # Priority: [Command Line Argument] -> [Environment Variable] -> [Default Values]
      # - SAPPORO_HOST=0.0.0.0 # Not available when using the uwsgi server.
      # - SAPPORO_PORT=1122 # Not available when using the uwsgi server.
      - SAPPORO_DEBUG=False
      - SAPPORO_RUN_DIR=${PWD}/run
      # - SAPPORO_GET_RUNS=False
      - SAPPORO_RUN_ONLY_REGISTERED_WORKFLOWS=True # デモ用に変更
      # - SAPPORO_ACCESS_CONTROL_ALLOW_ORIGIN=*
      # - SAPPORO_URL_PREFIX=/
      # デモ用に追加
      - SAPPORO_EXECUTABLE_WORKFLOWS=/demo-params/executable_workflows.json
    ports:
      - 0.0.0.0:1122:1122
    restart: on-failure
    working_dir: /app
    command:
      [
        "uwsgi",
        "--yaml",
        "/app/uwsgi.yml",
        "--http",
        "0.0.0.0:1122",
        "--workers",
        "1"
      ]
      # Number of workers to process http requests
    networks:
      - sapporo

networks:
  sapporo:
    name: sapporo-network
